USE [master]
GO

--ShoreTelECC
CREATE LOGIN [ShoreTelECC] WITH PASSWORD=N'ShoreTelECC', DEFAULT_DATABASE=[master], DEFAULT_LANGUAGE=[us_english], CHECK_EXPIRATION=OFF, CHECK_POLICY=OFF
GO

--WebsiteServices Users
CREATE LOGIN [webuser] WITH PASSWORD=N'webuser', DEFAULT_DATABASE=[master], CHECK_EXPIRATION=OFF, CHECK_POLICY=OFF
GO
--WSSReports (Reporting Services read access to WebsiteServices)
CREATE LOGIN [WSSReports] WITH PASSWORD=N'WSSReports', DEFAULT_DATABASE=[master], CHECK_EXPIRATION=OFF, CHECK_POLICY=OFF
GO
CREATE LOGIN [MIReportingAccess] WITH PASSWORD=N'MIReportingAccess', DEFAULT_DATABASE=[master], CHECK_EXPIRATION=OFF, CHECK_POLICY=OFF
GO
