-- Method 1

SELECT	OBJECT_NAME(sFK.parent_object_id) AS TableName
		,OBJECT_NAME(sFK.object_id) AS ForeignKeyName
		,COL_NAME(sFK.parent_object_id, sFKCol.parent_column_id)
		,*
FROM	sys.foreign_keys sFK
INNER JOIN
		sys.foreign_key_columns sFKcol
ON		sFK.object_id = sFKcol.constraint_object_id
ORDER BY
		3


-- Method 2

SELECT	CONSTRAINT_NAME = REF_CONST.CONSTRAINT_NAME,
		TABLE_CATALOG = FK.TABLE_CATALOG,
		TABLE_SCHEMA = FK.TABLE_SCHEMA,
		TABLE_NAME = FK.TABLE_NAME,
		COLUMN_NAME = FK_COLS.COLUMN_NAME,
		REFERENCED_TABLE_CATALOG = PK.TABLE_CATALOG,
		REFERENCED_TABLE_SCHEMA = PK.TABLE_SCHEMA,
		REFERENCED_TABLE_NAME = PK.TABLE_NAME,
		REFERENCED_COLUMN_NAME = PK_COLS.COLUMN_NAME
FROM	INFORMATION_SCHEMA.REFERENTIAL_CONSTRAINTS REF_CONST
INNER JOIN
		INFORMATION_SCHEMA.TABLE_CONSTRAINTS FK
ON		REF_CONST.CONSTRAINT_CATALOG = FK.CONSTRAINT_CATALOG
		AND REF_CONST.CONSTRAINT_SCHEMA = FK.CONSTRAINT_SCHEMA
		AND REF_CONST.CONSTRAINT_NAME = FK.CONSTRAINT_NAME
		AND FK.CONSTRAINT_TYPE = 'FOREIGN KEY'
INNER JOIN
		INFORMATION_SCHEMA.TABLE_CONSTRAINTS PK
ON		REF_CONST.UNIQUE_CONSTRAINT_CATALOG = PK.CONSTRAINT_CATALOG
		AND REF_CONST.UNIQUE_CONSTRAINT_SCHEMA = PK.CONSTRAINT_SCHEMA
		AND REF_CONST.UNIQUE_CONSTRAINT_NAME = PK.CONSTRAINT_NAME
		AND PK.CONSTRAINT_TYPE = 'PRIMARY KEY'
INNER JOIN
		INFORMATION_SCHEMA.KEY_COLUMN_USAGE FK_COLS
ON		REF_CONST.CONSTRAINT_NAME = FK_COLS.CONSTRAINT_NAME
INNER JOIN
		INFORMATION_SCHEMA.KEY_COLUMN_USAGE PK_COLS
ON		PK.CONSTRAINT_NAME = PK_COLS.CONSTRAINT_NAME
