USE [master]
GO

--ClientRetention user
CREATE LOGIN [ClientRetention] WITH PASSWORD=N'ClientRetention', DEFAULT_DATABASE=[master], CHECK_EXPIRATION=OFF, CHECK_POLICY=OFF
GO
--ClientRetention_MI Users
CREATE LOGIN [CR_BMI_DWExtract] WITH PASSWORD=N'CR_BMI_DWExtract', DEFAULT_DATABASE=[master], CHECK_EXPIRATION=OFF, CHECK_POLICY=OFF
GO

--iFACE_MI Users0
CREATE LOGIN [iFACE_BMI_DWEXTRACT] WITH PASSWORD=N'iFACE_BMI_DWEXTRACT', DEFAULT_DATABASE=[master], CHECK_EXPIRATION=OFF, CHECK_POLICY=OFF
GO
--CCCSIFACE user
CREATE LOGIN [iFACE_User] WITH PASSWORD=N'iFACE_User', DEFAULT_DATABASE=[master], CHECK_EXPIRATION=OFF, CHECK_POLICY=OFF
GO
CREATE LOGIN [MIReportingAccess] WITH PASSWORD=N'MIReportingAccess', DEFAULT_DATABASE=[master], CHECK_EXPIRATION=OFF, CHECK_POLICY=OFF
GO

--CCCSVABACS
CREATE LOGIN [cpfvabacsDbUser] WITH PASSWORD=N'cpfvabacsDbUser', DEFAULT_DATABASE=[master], CHECK_EXPIRATION=OFF, CHECK_POLICY=OFF
GO


--PDD Users
CREATE LOGIN [PddDbUser] WITH PASSWORD=N'PddDbUser', DEFAULT_DATABASE=[master], DEFAULT_LANGUAGE=[British], CHECK_EXPIRATION=OFF, CHECK_POLICY=OFF
GO
CREATE LOGIN [PDDUser] WITH PASSWORD=N'PDDUser', DEFAULT_DATABASE=[master], CHECK_EXPIRATION=OFF, CHECK_POLICY=OFF
GO


--iFACE User and Proxy Account...
CREATE LOGIN [CCCSNT\VMDCSiFACE_SSISProxy] FROM WINDOWS WITH DEFAULT_DATABASE=[master], DEFAULT_LANGUAGE=[us_english]

--User is rematched in restore script from DCSiFACE_SSISProxy to VMDCSiFACE_SSISProxy
--ALTER  USER [DCSiFACE_SSISProxy]
--WITH LOGIN = [CCCSNT\VMDCSiFACE_SSISProxy];

CREATE LOGIN [DCSSQLServerLink] WITH PASSWORD=N'DCSSQLServerLink', DEFAULT_DATABASE=[master], DEFAULT_LANGUAGE=[us_english], CHECK_EXPIRATION=OFF, CHECK_POLICY=OFF
GO
