GRANT SELECT, UPDATE, DELETE, INSERT ON dbo.CounterData TO [NT AUTHORITY\NETWORK SERVICE]
GO

GRANT SELECT, UPDATE, DELETE, INSERT ON dbo.CounterDetails TO [NT AUTHORITY\NETWORK SERVICE]
GO

GRANT SELECT, UPDATE, DELETE, INSERT  ON dbo.DisplayToID TO [NT AUTHORITY\NETWORK SERVICE]
GO