USE [master]
GO

--CWS Users
CREATE LOGIN [CWSRefreshUser] WITH PASSWORD=N'CWSRefreshUser', DEFAULT_DATABASE=[master], CHECK_EXPIRATION=OFF, CHECK_POLICY=OFF
GO
CREATE LOGIN [cwsuser] WITH PASSWORD=N'cwsuser', DEFAULT_DATABASE=[master], CHECK_EXPIRATION=OFF, CHECK_POLICY=OFF
GO
--DotNetNukeUsers
CREATE LOGIN [DNNServiceUser] WITH PASSWORD=N'DNNServiceUser', DEFAULT_DATABASE=[master], CHECK_EXPIRATION=OFF, CHECK_POLICY=OFF
GO
CREATE LOGIN [DotNetNukeApp] WITH PASSWORD=N'DotNetNukeApp', DEFAULT_DATABASE=[master], CHECK_EXPIRATION=OFF, CHECK_POLICY=OFF
GO
--WellBeing user
CREATE LOGIN [WbUser] WITH PASSWORD=N'WbUser', DEFAULT_DATABASE=[master], CHECK_EXPIRATION=OFF, CHECK_POLICY=OFF
GO


