USE [master]
GO

--ShoreTelECC
CREATE LOGIN [ShoreTelECC] WITH PASSWORD=N'ShoreTelECC', DEFAULT_DATABASE=[master], DEFAULT_LANGUAGE=[us_english], CHECK_EXPIRATION=OFF, CHECK_POLICY=OFF
GO

--DebtRemedy Users (for DAILY environment)
USE [master]
GO
CREATE LOGIN [DROUser] WITH PASSWORD=N'DROUser', DEFAULT_DATABASE=[master], CHECK_EXPIRATION=OFF, CHECK_POLICY=OFF
GO

--ACC Users
--CREATE LOGIN [AccountServicesUser] WITH PASSWORD=N'AccountServicesUser', DEFAULT_DATABASE=[ACC], CHECK_EXPIRATION=OFF, CHECK_POLICY=OFF
CREATE LOGIN [AccountServicesUser] WITH PASSWORD=N'AccountServicesUser', DEFAULT_DATABASE=[master], CHECK_EXPIRATION=OFF, CHECK_POLICY=OFF
GO
--ACC & DirectDebit Users
CREATE LOGIN [DdeDbUser] WITH PASSWORD=N'DdeDbUser', DEFAULT_DATABASE=[master], DEFAULT_LANGUAGE=[British], CHECK_EXPIRATION=OFF, CHECK_POLICY=OFF
GO
--DirectDebit Users
CREATE LOGIN [DMSDDE_LSUser] WITH PASSWORD=N'DMSDDE_LSUser', DEFAULT_DATABASE=[master], CHECK_EXPIRATION=OFF, CHECK_POLICY=OFF
GO
CREATE LOGIN [ReportingServices] WITH PASSWORD=N'ReportingServices', DEFAULT_DATABASE=[master], CHECK_EXPIRATION=OFF, CHECK_POLICY=OFF
GO

--RFI Users
CREATE LOGIN [ASPNet24] WITH PASSWORD=N'ASPNet24', DEFAULT_DATABASE=[master], CHECK_EXPIRATION=OFF, CHECK_POLICY=OFF
GO
CREATE LOGIN [RFI_BMI_DWExtract] WITH PASSWORD=N'RFI_BMI_DWExtract', DEFAULT_DATABASE=[master], CHECK_EXPIRATION=OFF, CHECK_POLICY=OFF
GO

--ClientRetention user
CREATE LOGIN [ClientRetention] WITH PASSWORD=N'ClientRetention', DEFAULT_DATABASE=[master], CHECK_EXPIRATION=OFF, CHECK_POLICY=OFF
GO
--ClientRetention_MI Users
CREATE LOGIN [CR_BMI_DWExtract] WITH PASSWORD=N'CR_BMI_DWExtract', DEFAULT_DATABASE=[master], CHECK_EXPIRATION=OFF, CHECK_POLICY=OFF
GO
--DDValidationLogger Users
--CREATE LOGIN [DDValidationLogger] WITH PASSWORD=N'DDValidationLogger', DEFAULT_DATABASE=[DDValidationLogger], CHECK_EXPIRATION=OFF, CHECK_POLICY=OFF
CREATE LOGIN [DDValidationLogger] WITH PASSWORD=N'DDValidationLogger', DEFAULT_DATABASE=[master], CHECK_EXPIRATION=OFF, CHECK_POLICY=OFF
GO
--iFACE_MI Users0
CREATE LOGIN [iFACE_BMI_DWEXTRACT] WITH PASSWORD=N'iFACE_BMI_DWEXTRACT', DEFAULT_DATABASE=[master], CHECK_EXPIRATION=OFF, CHECK_POLICY=OFF
GO
--CCCSIFACE user
CREATE LOGIN [iFACE_User] WITH PASSWORD=N'iFACE_User', DEFAULT_DATABASE=[master], CHECK_EXPIRATION=OFF, CHECK_POLICY=OFF
GO
CREATE LOGIN [MIReportingAccess] WITH PASSWORD=N'MIReportingAccess', DEFAULT_DATABASE=[master], CHECK_EXPIRATION=OFF, CHECK_POLICY=OFF
GO

--CCCSVABACS
CREATE LOGIN [cpfvabacsDbUser] WITH PASSWORD=N'cpfvabacsDbUser', DEFAULT_DATABASE=[master], CHECK_EXPIRATION=OFF, CHECK_POLICY=OFF
GO


--PDD Users
CREATE LOGIN [PddDbUser] WITH PASSWORD=N'PddDbUser', DEFAULT_DATABASE=[master], DEFAULT_LANGUAGE=[British], CHECK_EXPIRATION=OFF, CHECK_POLICY=OFF
GO
CREATE LOGIN [PDDUser] WITH PASSWORD=N'PDDUser', DEFAULT_DATABASE=[master], CHECK_EXPIRATION=OFF, CHECK_POLICY=OFF
GO

USE [master]
GO
IF @@SERVERNAME IN ('VM02GENPRODBA02', 'VM08GENPRODBA02')
BEGIN
	--DDE: DDOrganiser for UAT (from Windows)
	CREATE LOGIN [CCCSNT\uatDDOrganiser] FROM WINDOWS WITH DEFAULT_DATABASE=[master], DEFAULT_LANGUAGE=[us_english]
END
ELSE
BEGIN
	--DDE: DDOrganiser for SysTest (from Windows)
	CREATE LOGIN [CCCSNT\systestDDOrganiser] FROM WINDOWS WITH DEFAULT_DATABASE=[master], DEFAULT_LANGUAGE=[us_english]
END
GO

--iFACE User and Proxy Account...
CREATE LOGIN [CCCSNT\VMDCSiFACE_SSISProxy] FROM WINDOWS WITH DEFAULT_DATABASE=[master], DEFAULT_LANGUAGE=[us_english]

--User is rematched in restore script from DCSiFACE_SSISProxy to VMDCSiFACE_SSISProxy
--ALTER  USER [DCSiFACE_SSISProxy]
--WITH LOGIN = [CCCSNT\VMDCSiFACE_SSISProxy];

--CREATE LOGIN [ibacsuser] WITH PASSWORD=N'ibacsuser', DEFAULT_DATABASE=[master], CHECK_EXPIRATION=OFF, CHECK_POLICY=OFF
--GO

CREATE LOGIN [DCSSQLServerLink] WITH PASSWORD=N'DCSSQLServerLink', DEFAULT_DATABASE=[master], DEFAULT_LANGUAGE=[us_english], CHECK_EXPIRATION=OFF, CHECK_POLICY=OFF
GO
