USE [master]
GO
--DebtRemedy_Live users
CREATE LOGIN [DR_IVATRANSFER_WB_USER] WITH PASSWORD=N'DR_IVATRANSFER_WB_USER', DEFAULT_DATABASE=[master], CHECK_EXPIRATION=OFF, CHECK_POLICY=OFF
GO
CREATE LOGIN [ERE_User] WITH PASSWORD=N'ERE_User', DEFAULT_DATABASE=[master], CHECK_EXPIRATION=OFF, CHECK_POLICY=OFF
GO
CREATE LOGIN [VCUser] WITH PASSWORD=N'VCUser', DEFAULT_DATABASE=[master], DEFAULT_LANGUAGE=[British], CHECK_EXPIRATION=OFF, CHECK_POLICY=OFF
GO
--DROFS Logins
USE [master]
GO
CREATE LOGIN [DROUser] WITH PASSWORD=N'DROUser', DEFAULT_DATABASE=[master], CHECK_EXPIRATION=OFF, CHECK_POLICY=OFF
GO
--ShoreTelUser
CREATE LOGIN [shoretelUser] WITH PASSWORD=N'shoretelUser', DEFAULT_DATABASE=[master], DEFAULT_LANGUAGE=[us_english], CHECK_EXPIRATION=OFF, CHECK_POLICY=OFF
GO
